# -*- coding: utf-8 -*-
"""Modelos_Cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVpj-UJLbZDhjeYrzHF33LZsbSTlAQMS
"""

import pandas as pd

df=pd.read_csv("breast-cancer.csv")

df.head()

df.info()

df.shape

df.describe(include='all')

df['id'].value_counts().sum()

df.hist(figsize=(20,15))

df.isnull().sum()

df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

import seaborn as sn
import matplotlib.pyplot as plt
corr_matrix = df.corr()
fig, ax = plt.subplots(figsize = (20,10))
sn.heatmap(corr_matrix, annot=True)
plt.show()

